name: RSS 网站生成器

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "1 0 * * *"

jobs:
  gene-rss:
    runs-on: ubuntu-latest
    name: A job to gene RSS
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: 更新rss
      uses: tabhub/rssify@master
      with:
        title: CHAOSS Blog RSS
        url: https://www.zhihu.com/people/yumi_youmei/posts
        item-title-css: .ContentItem-title > span > a
        item-url-css: .ContentItem-title > span > a
